version: '2.0'

services:
  server:
    build:
      context: .
    env_file:
      - .env
    environment:
      - PORT=3000
    volumes:
      - upload:/app/upload
    ports:
      - 4000:3000
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  upload:
